#!/bin/bash

CPU_LOAD="$(uptime | rev | cut -d ':' -f 1 | rev | cut -d ',' -f1-2 | sed 's/,/./g')"
NUM_CORES="$(nproc)"
KERNEL_VER="$(uname -r)"
NUM_PROCESSES="$(ps -aux | sed '1d' | wc -l)"
LOGGED_USERS="$(who | wc -l)"
FREE_DISK="$(df -B1 --total | grep total | awk '{print $4}')"
TOTAL_DISK="$(df -B1 --total | grep total | awk '{print $2}')"
DNS_NAMES="$(hostname -d | tr ' ' '\n' | sed '/^$/d' | head -3 | sed -e "s/.*/\"&\"/" | tr '\n' ' ' | sed -e '$a\' | tr ' ' ',' | sed 's/.$//')"
DNS_NAMES_COUNT="$(hostname -d | tr ' ' '\n' | sed '/^$/d' | head -3 | wc -l)"
FREE_RAM="$(free -b | sed '1d' | sed '1q;d' | awk '{print $4}')"
TOTAL_RAM="$(free -b | sed '1d' | sed '1q;d' | awk '{print $2}')"
FREE_SWAP="$(free -b | sed '1d' | sed '2q;d' | awk '{print $4}')"
TOTAL_SWAP="$(free -b | sed '1d' | sed '2q;d' | awk '{print $2}')"

echo "cpu_load : double = $CPU_LOAD"
echo "num_cores : integer = $NUM_CORES"
echo "kernel_ver : string = $KERNEL_VER"
echo "num_processes : integer = $NUM_PROCESSES"
echo "logged_users : integer = $LOGGED_USERS"
echo "free_disk : integer = $FREE_DISK"
echo "total_disk : integer = $TOTAL_DISK"
echo "dns_names : set of $DNS_NAMES_COUNT string = {$DNS_NAMES}"
echo "free_ram : integer = $FREE_RAM"
echo "total_ram : integer = $TOTAL_RAM"
echo "free_swap : integer = $FREE_SWAP"
echo "total_swap : integer = $TOTAL_SWAP"
