//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Query.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="QueryParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IQueryVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] QueryParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] QueryParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere_clause([NotNull] QueryParser.Where_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.order_by_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_by_clause([NotNull] QueryParser.Order_by_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.order_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_item([NotNull] QueryParser.Order_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.order"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder([NotNull] QueryParser.OrderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.nulls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNulls([NotNull] QueryParser.NullsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.sel_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSel_item([NotNull] QueryParser.Sel_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.sel_modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSel_modifier([NotNull] QueryParser.Sel_modifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.cond_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCond_expr([NotNull] QueryParser.Cond_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.cond_expr_no_gt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCond_expr_no_gt([NotNull] QueryParser.Cond_expr_no_gtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_expr([NotNull] QueryParser.And_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.and_expr_no_gt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd_expr_no_gt([NotNull] QueryParser.And_expr_no_gtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.not_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot_expr([NotNull] QueryParser.Not_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.not_expr_no_gt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot_expr_no_gt([NotNull] QueryParser.Not_expr_no_gtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.bool_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_expr([NotNull] QueryParser.Bool_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.bool_expr_no_gt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_expr_no_gt([NotNull] QueryParser.Bool_expr_no_gtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.basic_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasic_expr([NotNull] QueryParser.Basic_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.fact_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFact_expr([NotNull] QueryParser.Fact_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.neg_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNeg_expr([NotNull] QueryParser.Neg_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.term_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm_expr([NotNull] QueryParser.Term_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] QueryParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.string_const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString_const([NotNull] QueryParser.String_constContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.bool_const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool_const([NotNull] QueryParser.Bool_constContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.int_const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt_const([NotNull] QueryParser.Int_constContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.double_const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble_const([NotNull] QueryParser.Double_constContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.expr_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_list([NotNull] QueryParser.Expr_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.expr_list_no_gt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_list_no_gt([NotNull] QueryParser.Expr_list_no_gtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.rel_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRel_op([NotNull] QueryParser.Rel_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.rel_op_no_gt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRel_op_no_gt([NotNull] QueryParser.Rel_op_no_gtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QueryParser.error"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError([NotNull] QueryParser.ErrorContext context);
}
