//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Query.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IQueryListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class QueryBaseListener : IQueryListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] QueryParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] QueryParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.statement_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement_list([NotNull] QueryParser.Statement_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.statement_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement_list([NotNull] QueryParser.Statement_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] QueryParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] QueryParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.where_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhere_clause([NotNull] QueryParser.Where_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.where_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhere_clause([NotNull] QueryParser.Where_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.order_by_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrder_by_clause([NotNull] QueryParser.Order_by_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.order_by_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrder_by_clause([NotNull] QueryParser.Order_by_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.order_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrder_list([NotNull] QueryParser.Order_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.order_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrder_list([NotNull] QueryParser.Order_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.order_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrder_item([NotNull] QueryParser.Order_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.order_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrder_item([NotNull] QueryParser.Order_itemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.order"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrder([NotNull] QueryParser.OrderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.order"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrder([NotNull] QueryParser.OrderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.nulls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNulls([NotNull] QueryParser.NullsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.nulls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNulls([NotNull] QueryParser.NullsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.sel_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_list([NotNull] QueryParser.Sel_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.sel_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_list([NotNull] QueryParser.Sel_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.sel_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_item([NotNull] QueryParser.Sel_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.sel_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_item([NotNull] QueryParser.Sel_itemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.sel_modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_modifier([NotNull] QueryParser.Sel_modifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.sel_modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_modifier([NotNull] QueryParser.Sel_modifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.sel_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel_expr([NotNull] QueryParser.Sel_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.sel_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel_expr([NotNull] QueryParser.Sel_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.cond_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCond_expr([NotNull] QueryParser.Cond_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.cond_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCond_expr([NotNull] QueryParser.Cond_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.cond_expr_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCond_expr_no_gt([NotNull] QueryParser.Cond_expr_no_gtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.cond_expr_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCond_expr_no_gt([NotNull] QueryParser.Cond_expr_no_gtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expr([NotNull] QueryParser.And_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expr([NotNull] QueryParser.And_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.and_expr_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expr_no_gt([NotNull] QueryParser.And_expr_no_gtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.and_expr_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expr_no_gt([NotNull] QueryParser.And_expr_no_gtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.not_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot_expr([NotNull] QueryParser.Not_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.not_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot_expr([NotNull] QueryParser.Not_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.not_expr_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot_expr_no_gt([NotNull] QueryParser.Not_expr_no_gtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.not_expr_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot_expr_no_gt([NotNull] QueryParser.Not_expr_no_gtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.bool_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_expr([NotNull] QueryParser.Bool_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.bool_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_expr([NotNull] QueryParser.Bool_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.bool_expr_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_expr_no_gt([NotNull] QueryParser.Bool_expr_no_gtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.bool_expr_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_expr_no_gt([NotNull] QueryParser.Bool_expr_no_gtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.basic_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasic_expr([NotNull] QueryParser.Basic_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.basic_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasic_expr([NotNull] QueryParser.Basic_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.fact_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFact_expr([NotNull] QueryParser.Fact_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.fact_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFact_expr([NotNull] QueryParser.Fact_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.neg_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNeg_expr([NotNull] QueryParser.Neg_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.neg_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNeg_expr([NotNull] QueryParser.Neg_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.term_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm_expr([NotNull] QueryParser.Term_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.term_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm_expr([NotNull] QueryParser.Term_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] QueryParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] QueryParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.string_const"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_const([NotNull] QueryParser.String_constContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.string_const"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_const([NotNull] QueryParser.String_constContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.bool_const"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_const([NotNull] QueryParser.Bool_constContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.bool_const"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_const([NotNull] QueryParser.Bool_constContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.int_const"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt_const([NotNull] QueryParser.Int_constContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.int_const"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt_const([NotNull] QueryParser.Int_constContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.double_const"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDouble_const([NotNull] QueryParser.Double_constContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.double_const"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDouble_const([NotNull] QueryParser.Double_constContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.expr_list_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_list_opt([NotNull] QueryParser.Expr_list_optContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.expr_list_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_list_opt([NotNull] QueryParser.Expr_list_optContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.expr_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_list([NotNull] QueryParser.Expr_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.expr_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_list([NotNull] QueryParser.Expr_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.expr_list_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_list_no_gt([NotNull] QueryParser.Expr_list_no_gtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.expr_list_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_list_no_gt([NotNull] QueryParser.Expr_list_no_gtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.rel_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRel_op([NotNull] QueryParser.Rel_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.rel_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRel_op([NotNull] QueryParser.Rel_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.rel_op_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRel_op_no_gt([NotNull] QueryParser.Rel_op_no_gtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.rel_op_no_gt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRel_op_no_gt([NotNull] QueryParser.Rel_op_no_gtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QueryParser.error"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterError([NotNull] QueryParser.ErrorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QueryParser.error"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitError([NotNull] QueryParser.ErrorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
